const light_palatte = {
  primaryBgColor: "#f8faff",
  primaryBlue: "#48C0E8",
  primaryRed: "red",
  primaryGray: "#F9FAFF",
  primaryBlack: "rgba(0, 0, 0, 1)",
  primaryLightBlack: "rgba(0, 0, 0, 0.75)",
  primaryWhite: "rgba(255, 255, 255, 1)",
  primaryLightGray: "#D4D7E5",
  secondaryLightGray: "#9397AD",
  warningColor: "#DCA048",
  successColor: "#48B16E",
  errorColor: "#FB3836",
  secondaryBlue: "rgba(72, 192, 232, 0.1)",
  secondaryRed: "rgba(251, 56, 54, 0.1)",
  textPrimaryColor: "#131022",
  ratingStarPrimaryColor: "#faaf00",
  primaryGreenColor: "#22c55e",
};

export const theme = {
  primaryBgColor: light_palatte?.primaryBgColor,
  primaryBlue: light_palatte?.primaryBlue,
  primaryGray: light_palatte?.primaryGray,
  primaryLightBlack: light_palatte?.primaryLightBlack,
  primaryWhite: light_palatte?.primaryWhite,
  primaryBlack: light_palatte?.primaryBlack,
  primaryLightGray: light_palatte?.primaryLightGray,
  secondaryLightGray: light_palatte?.secondaryLightGray,
  warningColor: light_palatte?.warningColor,
  successColor: light_palatte?.successColor,
  errorColor: light_palatte?.errorColor,
  secondaryBlue: light_palatte?.secondaryBlue,
  secondaryRed: light_palatte?.secondaryRed,
  primaryRed: light_palatte?.primaryRed,
  textPrimaryColor: light_palatte?.textPrimaryColor,
  ratingStarPrimaryColor: light_palatte?.ratingStarPrimaryColor,
  primaryGreenColor: light_palatte?.primaryGreenColor
};